[package]
name = "object-oriented-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.0" }
derivative = "2.2.0"

serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_repr = "0.1.7"